### ISSUE TITLE
UI is extremely fuzzy when viewed on a monitor with portrait display orientation

### ISSUE THREAD

**Issue by RAS-2112** [MahdiGhiasi/Xpotify#44]
**Description**
When viewing Xpo Music on a monitor in portrait display orientation, the main UI is extremely fuzzy. This includes text and images. The left hand menu, settings menu and now playing bar remain unaffected.

This issue is not seen on the same monitor in landscape display orientation.

**To Reproduce**
1. Use Xpo music on monitor in portrait mode (Windows Settings > System > Display > Display orientation > Portrait)

**Screenshots**
![Portrait](https://user-images.githubusercontent.com/12658883/61996736-9948ae80-b08f-11e9-8bff-4de02fef9430.jpg)
![Landscape](https://user-images.githubusercontent.com/12658883/61996743-abc2e800-b08f-11e9-94ec-ec5016bcb51c.jpg)

**Build:**
 - OS: Windows 10 Pro (1903 - 18362.10006)
 - Xpo Music Version: 2.0.1.0

**Additional context**
Multi-monitor setup with the portrait monitor using the following settings in Windows display:
- Scale: 100%
- Advanced option, Fix scaling for apps: Enabled*
- Display Resolution: Portrait (flipped)

\* Disabling this option has no impact

![image](https://user-images.githubusercontent.com/12658883/61996752-d6ad3c00-b08f-11e9-8474-19fcd94ef12e.png)

**Comment by MahdiGhiasi** [comment]
Thanks for the detailed report.

This issue is related to EdgeHTML rendering of CSS property `filter` and `backdrop-filter` when the content is too tall, so this only happens to light theme.

I'm going to experiment with two divs with `backdrop-filter` each covering half of the page, and see whether that hack solves this. (If it doesn't, I have no idea what else could be done for fixing this, other than MS fixing EdgeHTML)

**Comment by MahdiGhiasi** [comment]
This is fixed and will be available in the next update soon.
